export type SimplerPhraseRule = {
  readonly phrase: string
  readonly replacements: readonly [string, ...string[]]
}

export const SIMPLER_PHRASES = [
  { phrase: "a large number of", replacements: ["many"] },
  { phrase: "at the present time", replacements: ["now"] },
  { phrase: "at this point in time", replacements: ["now"] },
  { phrase: "at this time", replacements: ["now"] },
  { phrase: "by means of", replacements: ["by", "with"] },
  { phrase: "despite the fact that", replacements: ["although"] },
  { phrase: "due to the fact that", replacements: ["because"] },
  { phrase: "for the purpose of", replacements: ["to", "for"] },
  { phrase: "has the ability to", replacements: ["can"] },
  { phrase: "in a manner that", replacements: ["so that"] },
  { phrase: "in accordance with", replacements: ["under", "following"] },
  { phrase: "in addition to", replacements: ["besides"] },
  { phrase: "in light of the fact that", replacements: ["because"] },
  { phrase: "in order for", replacements: ["for"] },
  { phrase: "in order to", replacements: ["to"] },
  { phrase: "in relation to", replacements: ["about"] },
  { phrase: "in the event that", replacements: ["if"] },
  { phrase: "in the event of", replacements: ["if"] },
  { phrase: "in the near future", replacements: ["soon"] },
  { phrase: "is able to", replacements: ["can"] },
  { phrase: "on a regular basis", replacements: ["regularly"] },
  { phrase: "prior to", replacements: ["before"] },
  { phrase: "subsequent to", replacements: ["after"] },
  { phrase: "the majority of", replacements: ["most"] },
  { phrase: "until such time as", replacements: ["until"] },
  { phrase: "with regard to", replacements: ["about"] },
  { phrase: "with respect to", replacements: ["about"] },
  { phrase: "additional", replacements: ["more", "extra"] },
  { phrase: "approximately", replacements: ["about"] },
  { phrase: "commence", replacements: ["begin", "start"] },
  { phrase: "concerning", replacements: ["about"] },
  { phrase: "consequently", replacements: ["so"] },
  { phrase: "demonstrate", replacements: ["show"] },
  { phrase: "endeavor", replacements: ["try"] },
  { phrase: "facilitate", replacements: ["help"] },
  { phrase: "finalize", replacements: ["finish"] },
  { phrase: "frequently", replacements: ["often"] },
  { phrase: "initially", replacements: ["at first"] },
  { phrase: "nevertheless", replacements: ["still", "but"] },
  { phrase: "numerous", replacements: ["many"] },
  { phrase: "obtain", replacements: ["get"] },
  { phrase: "purchase", replacements: ["buy"] },
  { phrase: "regarding", replacements: ["about"] },
  { phrase: "require", replacements: ["need"] },
  { phrase: "terminate", replacements: ["end", "stop"] },
  { phrase: "utilize", replacements: ["use"] }
] as const satisfies readonly SimplerPhraseRule[]

export const QUALIFIERS: ReadonlySet<string> = new Set([
  "actually",
  "apparently",
  "basically",
  "fairly",
  "maybe",
  "perhaps",
  "possibly",
  "probably",
  "quite",
  "really",
  "somewhat",
  "very"
])
